development:
  adapter: postgresql
  encoding: unicode
  database: gems_test_staging_dev
  pool: 5
  host: localhost
  username: fpgentil
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gems_test_staging_test
  pool: 5
  host: localhost
  username: fpgentil
  password:
